#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="$root/artifacts/tests/large-locals"
mkdir -p "$output"
dotnet build "$root/src/LlvmNet.Compiler" -c Release --nologo
awk 'BEGIN {
    print "target triple = \"x86_64-pc-linux-gnu\""
    print "@_ZTIi = external constant ptr"
    print "declare i32 @__gxx_personality_v0(...)"
    print "declare ptr @__cxa_allocate_exception(i64)"
    print "declare void @__cxa_throw(ptr, ptr, ptr)"
    print "declare ptr @__cxa_begin_catch(ptr)"
    print "declare void @__cxa_end_catch()"
    print "define i64 @produce(i1 %fail) {"
    print "entry:"
    print "  br i1 %fail, label %throw, label %normal"
    print "normal:"
    print "  ret i64 41"
    print "throw:"
    print "  %exception = call ptr @__cxa_allocate_exception(i64 4)"
    print "  store i32 19, ptr %exception"
    print "  call void @__cxa_throw(ptr %exception, ptr @_ZTIi, ptr null)"
    print "  unreachable"
    print "}"
    print "define i32 @exercise(i1 %fail) personality ptr @__gxx_personality_v0 {"
    print "entry:"
    print "  %seed = add i64 0, 7"
    print "  %live = add i64 %seed, 11"
    print "  %value0 = add i64 %seed, 0"
    for (step = 1; step <= 70000; step++)
        printf "  %%value%d = add i64 %%value%d, 1\n", step, step - 1
    print "  br label %check"
    print "check:"
    print "  %merged = phi i64 [ %value70000, %entry ]"
    print "  %sum0 = add i64 0, 0"
    for (step = 1; step <= 70000; step++)
        printf "  %%sum%d = add i64 %%sum%d, %%value%d\n", step, step - 1, step
    print "  %sum_ok = icmp eq i64 %sum70000, 2450525000"
    print "  %value_ok = icmp eq i64 %merged, 70007"
    print "  %live_ok = icmp eq i64 %live, 18"
    print "  %seed_ok = icmp eq i64 %seed, 7"
    print "  %partial = and i1 %value_ok, %live_ok"
    print "  %partial2 = and i1 %partial, %seed_ok"
    print "  %values_valid = and i1 %partial2, %sum_ok"
    print "  br label %swap"
    print "swap:"
    print "  %left = phi i64 [ %seed, %check ], [ %right, %swap ]"
    print "  %right = phi i64 [ %live, %check ], [ %left, %swap ]"
    print "  %iteration = phi i32 [ 0, %check ], [ %next, %swap ]"
    print "  %next = add i32 %iteration, 1"
    print "  %finished = icmp eq i32 %iteration, 3"
    print "  br i1 %finished, label %call, label %swap"
    print "call:"
    print "  %left_ok = icmp eq i64 %left, 18"
    print "  %right_ok = icmp eq i64 %right, 7"
    print "  %phi_valid = and i1 %left_ok, %right_ok"
    print "  %valid = and i1 %values_valid, %phi_valid"
    print "  %returned = invoke i64 @produce(i1 %fail) to label %normal unwind label %caught"
    print "normal:"
    print "  %return_ok = icmp eq i64 %returned, 41"
    print "  %expected_normal = xor i1 %fail, true"
    print "  %normal_valid = and i1 %return_ok, %expected_normal"
    print "  br label %done"
    print "caught:"
    print "  %landing = landingpad { ptr, i32 } catch ptr null"
    print "  %handle = extractvalue { ptr, i32 } %landing, 0"
    print "  %object = call ptr @__cxa_begin_catch(ptr %handle)"
    print "  %exception_value = load i32, ptr %object"
    print "  call void @__cxa_end_catch()"
    print "  %exception_ok = icmp eq i32 %exception_value, 19"
    print "  %catch_valid = and i1 %exception_ok, %fail"
    print "  br label %done"
    print "done:"
    print "  %call_valid = phi i1 [ %normal_valid, %normal ], [ %catch_valid, %caught ]"
    print "  %all_valid = and i1 %valid, %call_valid"
    print "  %result = select i1 %all_valid, i32 0, i32 1"
    print "  ret i32 %result"
    print "}"
    print "define i32 @main() {"
    print "entry:"
    print "  %normal = call i32 @exercise(i1 false)"
    print "  %caught = call i32 @exercise(i1 true)"
    print "  %result = or i32 %normal, %caught"
    print "  ret i32 %result"
    print "}"
}' > "$output/large.input"
clang-22 -x ir -O0 "$output/large.input" -lstdc++ -o "$output/native"
"$output/native"
for runtime in system portable; do
    target="$output/large-$runtime"
    "$root/bin/llvmnet" --runtime="$runtime" -x ir -O0 -c "$output/large.input" -o "$target.bc"
    "$root/bin/llvmnet" --runtime="$runtime" "$target.bc" -o "$target.dll"
    dotnet "$target.dll"
    "$root/bin/llvmnet" --runtime="$runtime" --nativeaot "$target.bc" -o "$target-aot"
    "$target-aot"
    dotnet run --project "$root/tests/LlvmNet.Checks" -c Release -- inspect-methods "$target.dll" exercise > "$target-metadata.txt"
    awk '/^exercise:/ { split($2, count, "="); if (count[2] >= 65535) exit 1; found=1 } END { if (!found) exit 1 }' "$target-metadata.txt"
    printf 'PASS: %s large function storage, cyclic PHIs and normal/unwind results in JIT/NativeAOT\n' "$runtime"
done