#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
output="$root/artifacts/tests/math"
mkdir -p "$output"
dotnet build "$root/src/LlvmNet.Compiler" -c Release --nologo
clang-22 -O1 "$root/tests/c/math.c" -lm -o "$output/native"
"$output/native"
dotnet "$root/src/LlvmNet.Compiler/bin/Release/net10.0/llvmnet.dll" "$root/tests/c/math.c" -lm -o "$output/math.dll"
dotnet "$output/math.dll"
"$root/bin/llvmnet" --runtime=portable -fno-builtin "$root/tests/c/math.c" -o "$output/math-portable.dll"
dotnet "$output/math-portable.dll"
clang-22 -O1 "$root/tests/c/rounding.c" -lm -o "$output/rounding-native"
"$output/rounding-native"
"$root/bin/llvmnet" --runtime=system -O1 "$root/tests/c/rounding.c" -o "$output/rounding.dll"
dotnet "$output/rounding.dll"
"$root/bin/llvmnet" --runtime=system --nativeaot -O1 "$root/tests/c/rounding.c" -o "$output/rounding-aot"
"$output/rounding-aot"
cp "$root/tests/ir/rounding.ll" "$output/rounding.input"
"$root/bin/llvmnet" --runtime=portable -x ir -O0 -c "$output/rounding.input" -o "$output/rounding-portable.bc"
"$root/bin/llvmnet" --runtime=portable "$output/rounding-portable.bc" -o "$output/rounding-portable.dll"
dotnet "$output/rounding-portable.dll"
"$root/bin/llvmnet" --runtime=portable --nativeaot "$output/rounding-portable.bc" -o "$output/rounding-portable-aot"
"$output/rounding-portable-aot"
printf 'PASS: ffmpeg scalar math probes, rounding and sqrt errno\n'