set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
get_filename_component(LLVMNET_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(CMAKE_C_COMPILER "${LLVMNET_ROOT}/bin/llvmnet")
set(CMAKE_CXX_COMPILER "${LLVMNET_ROOT}/bin/llvmnet")
set(CMAKE_AR llvm-ar-22 CACHE FILEPATH "LLVM bitcode archiver")
set(CMAKE_RANLIB llvm-ranlib-22 CACHE FILEPATH "LLVM bitcode archive indexer")
set(CMAKE_NM llvm-nm-22 CACHE FILEPATH "LLVM bitcode symbol reader")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_CROSSCOMPILING_EMULATOR dotnet)
set(CMAKE_C_FLAGS_INIT "-O1 -fno-vectorize -fno-slp-vectorize -fno-stack-protector")
set(CMAKE_CXX_FLAGS_INIT "-O1 -fno-vectorize -fno-slp-vectorize -fno-stack-protector")